In [33]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [34]:
print(tf.__version__)

2.2.0


In [35]:
link = r"D:\MY_WORK\MyContents\ML&AI\Machine_Learning\ML_Dataset\ANN\Churn_Modelling.csv"
dataset = pd.read_csv(link)
X = dataset.iloc[:,3:-1].values
Y = dataset.iloc[:, -1].values

In [36]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [37]:
print(Y)

[1 0 1 ... 1 1 0]


In [38]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [41]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [42]:
ann = tf.keras.models.Sequential()     #initializing the ANN

In [43]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))    #adding the input and 1st hidden layer 

In [44]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))     #adding the second hidden layer

In [45]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))    #adding the output layer 

In [46]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy' , metrics =['accuracy'])    #compiling the ANN

In [47]:
ann.fit(X_train, Y_train, batch_size = 32 , epochs = 100)

Epoch 1/100
250/250 [==============================] - ETA: 0s - loss: 0.5379 - accuracy: 0.78 - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7840
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4528 - accuracy: 0.7984
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4367 - accuracy: 0.8073
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4295 - accuracy: 0.8111
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4239 - accuracy: 0.8150
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4191 - accuracy: 0.8191
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4147 - accuracy: 0.8240
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4104 - accuracy: 0.8281
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4063 - accuracy: 0.8306
Epoch 10/100
250/250 [===========================

Epoch 81/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3418 - accuracy: 0.8597
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3409 - accuracy: 0.8595
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3409 - accuracy: 0.8608
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3405 - accuracy: 0.8615
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3402 - accuracy: 0.8614
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8611
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3401 - accuracy: 0.8609
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3398 - accuracy: 0.8611
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3394 - accuracy: 0.8625
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3390

In [132]:
y_pred = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
if (y_pred > 0.5) :
    print(" The customer will leave the bank")
else:
    print(" The customer will stay with the bank")

 The customer will stay with the bank


In [133]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [134]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, y_pred)
print(cm)
accuracy_score(Y_test, y_pred)

[[1522   73]
 [ 208  197]]


0.8595